kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s3-data
  namespace: s3-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
