kind: Secret
apiVersion: v1
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: S9...
  access_key_secret: r...
  bucketnames: loki-bucket
  endpoint: https://s3.domain.com:9000
  region: us-west
