kind: Secret
apiVersion: v1
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: S9...
  access_key_secret: r...
  bucketnames: loki-bucket
  endpoint: http://s3.s3-storage.svc.cluster.local:9000
  region: us-west
