apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-netobserv-operator
    openshift.io/cluster-monitoring: "true"
  name: openshift-netobserv-operator
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: netobserv
    openshift.io/cluster-monitoring: "true"
  name: netobserv