apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: stack
  namespace: observability
spec:
  storageSize: 1Gi
  storage:
      secret:
          name: tracing-s3
          type: s3
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
template:
    queryFrontend:
      jaegerQuery:
        # Enable the Jaeger UI
        enabled: true